### PR TITLE
MKS-28 Create database backup

### PR DESCRIPTION
**Pull request by sergiynikon**

### CODE REVIEW

**Review by bvzayats — COMMENTED** [review]
So did you create a table in your DB?

**Comment by sergiynikon** [comment]
> So did you create a table in your DB?

wait, I am going to add new commit with required columns and one not required, sorry, (but table was created)

**Comment by sergiynikon** [comment]
> > So did you create a table in your DB?
> 
> wait, I am going to add new commit with required columns and one not required, sorry, (but table was created)

Done.

**Comment by Magfiozy** [comment]
The stored procedure works incorrectly: when I tried to get the second page with 4 users I got the next result:
 `18D405F7-49B1-4D25-BBAE-2578B83D69A5	user2@gmail.com	user2pass	
user	two	+380974287234
AF684A67-F875-42A1-97B3-2ABC5B6D7DB5	user3@gmail.com	user3pass	
user	three	+380974287984
D3619590-925A-4A3E-926F-2F3F70F50731	user4@gmail.com	user4pass	
user	four	+380974297532
9AC9EB76-185B-42B3-8FE7-31517395DF2D	user5@gmail.com	user5pass	
user	five	+380974287932`

**Review by Magfiozy — APPROVED** [review]

**Review by bvzayats — APPROVED** [review]

**Pull request merged**
