### PR TITLE
Dev/bohdan h/mks 1 init personal branch

### PR DESCRIPTION
**Pull request by BohdanHamurda**

### CODE REVIEW

**Review by bvzayats — COMMENTED** [review]
Wrong commit messages template

**Review by bvzayats — APPROVED** [review]

**Review by FoxLviv — COMMENTED** [review]
change your text pls

**Comment by sergiynikon** [comment]
> > change your text pls
> 
> What do you mean?

image
I think you have to translate text into english

**Comment by chudik47** [comment]
> > > change your text pls
> > 
> > 
> > What do you mean?
> 
> image
> I think you have to translate text into english

Actually, I haven't to do it. Maybe you mean @BohdanHamurda . Also, I think for now it isn't necessary, but in the future, it will be noticed, if somebody makes any mistakes including encoding.

**Review by TsisinskyjV — APPROVED** [review]

**Pull request merged**
